import type { Clearance, Finding, ScanResult } from "@/lib/types";
import { SITE } from "@/lib/site";

type ExportableResult = ScanResult & { reportUrl?: string };

function stampLabel(clearance: Clearance): string {
  if (clearance === "go") return "CLEARED";
  if (clearance === "hold") return "HOLD";
  return "DENIED";
}

function stampSub(clearance: Clearance): string {
  if (clearance === "go") return "Ship It";
  if (clearance === "hold") return "Fix Then Ship";
  return "Don't Ship";
}

function findingBlock(f: Finding, index: number): string {
  const lines = [
    `### ${index}. [${f.severity.toUpperCase()}] ${f.title}`,
    "",
    f.summary,
  ];
  if (f.impact) {
    lines.push("", `**Impact:** ${f.impact}`);
  }
  if (f.evidence) {
    lines.push("", "**Evidence:**", "```", f.evidence, "```");
  }
  if (f.fix?.code) {
    lines.push(
      "",
      `**Fix (${f.fix.label}):**`,
      "```" +
        (["txt", "html", "nginx", "java"].includes(f.fix.language)
          ? ""
          : f.fix.language),
      f.fix.code,
      "```"
    );
  }
  if (f.fixes && f.fixes.length > 1) {
    lines.push("", "_Other stacks:_ " + f.fixes.slice(1).map((x) => x.label).join(" · "));
  }
  return lines.join("\n");
}

/** Markdown report for GitHub Issues / Linear / Notion / email. */
export function formatClearanceMarkdown(result: ExportableResult): string {
  const stamp = stampLabel(result.clearance);
  const priority = result.priorityFixIds
    .map((id) => result.findings.find((f) => f.id === id))
    .filter((f): f is Finding => Boolean(f));

  const lines: string[] = [
    `# Site Clearance — ${stamp}`,
    "",
    `| Field | Value |`,
    `| --- | --- |`,
    `| URL | ${result.urlFinal} |`,
    `| Verdict | **${stamp}** (${stampSub(result.clearance)}) |`,
    `| Score | ${result.score}/100 |`,
    `| Blockers | ${result.summary.blockers} |`,
    `| Warnings | ${result.summary.warnings} |`,
    `| Platform | ${result.platform ?? "unknown"} |`,
    `| Scanned | ${result.scannedAt} |`,
  ];

  if (result.reportUrl) {
    lines.push(`| Report | ${result.reportUrl} |`);
  }

  lines.push("", "## Fix these first", "");

  if (priority.length === 0) {
    lines.push("_No priority fixes — clean clearance._");
  } else {
    priority.forEach((f, i) => {
      lines.push(findingBlock(f, i + 1), "");
    });
  }

  const rest = result.findings.filter(
    (f) => !result.priorityFixIds.includes(f.id)
  );
  if (rest.length > 0) {
    lines.push("## Additional findings", "");
    rest.forEach((f, i) => {
      lines.push(findingBlock(f, i + 1), "");
    });
  }

  lines.push(
    "---",
    `_Generated by [${SITE.name}](${SITE.domain.replace(/\/$/, "")})_`
  );

  return lines.join("\n");
}

/** Prompt pasteable into Cursor / Claude Code / Copilot Chat. */
export function formatCursorPrompt(result: ExportableResult): string {
  const stamp = stampLabel(result.clearance);
  const priority = result.priorityFixIds
    .map((id) => result.findings.find((f) => f.id === id))
    .filter((f): f is Finding => Boolean(f));

  const targets = priority.length > 0 ? priority : result.findings.slice(0, 5);

  const lines: string[] = [
    `You are fixing go-live clearance failures for a production site.`,
    ``,
    `Site: ${result.urlFinal}`,
    `Clearance: ${stamp} (${result.score}/100) — ${stampSub(result.clearance)}`,
    `Platform hint: ${result.platform ?? "unknown"}`,
    `Prefer the primary fix channel for each issue (HTML / Next.js / Server). Use the AI prompt channel when you want an agent to apply the fix. Do not assume Next.js unless the repo is Next/Vercel.`,
    ``,
    `Work through these issues in order. For each: confirm the evidence in the codebase, apply the minimal fix, and do not introduce unrelated refactors.`,
    ``,
  ];

  if (targets.length === 0) {
    lines.push(`No open findings. Double-check metadata, robots, and security headers are production-ready.`);
  } else {
    targets.forEach((f, i) => {
      lines.push(
        `## ${i + 1}. ${f.title} [${f.severity}]`,
        `Problem: ${f.summary}`,
        f.impact ? `Why it matters: ${f.impact}` : "",
        f.evidence ? `Evidence:\n${f.evidence}` : "",
        f.fix?.code
          ? `Suggested fix (${f.fix.label} — switch stack in the report if needed):\n\`\`\`\n${f.fix.code}\n\`\`\`${
              f.fixes && f.fixes.length > 1
                ? `\nAlso available: ${f.fixes
                    .slice(1)
                    .map((x) => x.label)
                    .join(", ")}`
                : ""
            }`
          : "Suggested fix: inspect metadata / headers / routes for this check.",
        ``
      );
    });
  }

  lines.push(
    `After fixes: re-run the public URL through Go-Live Clearance and confirm the stamp is CLEARED (or HOLD only for intentional warnings).`
  );

  return lines.filter((l) => l !== undefined).join("\n");
}
